### ISSUE TITLE
[Suggestion] How about creating an Enum Type for the language field in the Analyzer?

### ISSUE THREAD

**Issue by nerdchanii** [balpan-rs/balpan#28]
Hello! I'm leaving a suggestion to manage the Language field in the Analyzer as Enum. 

If we manage the language fields in the analyzer with Enum, we can manage the match statements with `Language::Rust`, `Language::Python`, and `Language::Other(other_lang)`. which will enable more stable matches.

### now
https://github.com/balpan-rs/balpan/blob/ec3c71cc8da833b571994bc76fe85f7b079c080e/src/analyzer.rs#L9-L13

### suggestion

```rust
 pub struct Analyzer { 
     pub source_code: String, 
     pub language: Language,
 } 
``` 
 
 
### Language Enum's blueprint

```rust
/// language enums
enum Language {
    Rust,
    Python,
    Other(String),
}

impl Language {
    fn as_str(&self) -> &str {
        match self {
            Language::Rust => "rust",
            Language::Python => "python",
            Language::Other(other) => other.as_str(),
        }
    }

    fn from_string(&self, lang: String) -> Self {
        match lang.as_str() {
            "rust" => Language::Rust,
            "python" => Language::Python,
            _ => Language::Other(String::from(lang)),
        }
    }
}
```

### Benefit
By doing this, it enables more dependable pattern matching as illustrated below. Moreover, it seems that there would be no need to modify the existing conversion code that uses as_str().

```rust 
fn top_level_node_type(&self) -> &str {
        match self.language {
            Language::Rust => "source_file",
            Language::Python => "module",
            Language::Other(_) => "",
        }
    }
```

**Comment by malkoG** [comment]
I agree with your suggestion. This could be nice.

I'm currently working on CLI subcommands #27, So, If you want to contribute, you can.
